# Generated by Django 2.2.3 on 2020-02-12 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articlesApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('product UI', 'product UI'), ('venture capital', 'venture capital'), ('information', 'information'), ('bugs and fixes', 'bugs and fixes'), ('other', 'other')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='LCRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=60, null=True)),
                ('room_name', models.CharField(max_length=60, null=True)),
                ('api_created', models.BooleanField(default=False)),
                ('privacy', models.CharField(max_length=60, null=True)),
                ('url', models.CharField(max_length=60, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('date_to_appointment', models.DateTimeField(null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articlesApi.Article')),
                ('participants', models.ManyToManyField(related_name='room_participants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingReviewChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issues', models.CharField(blank=True, choices=[('User', 'User'), ('Network and Connection', 'Network and Connection'), ('other', 'Other')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_to_appointment', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
                ('scheduled', models.BooleanField(default=False)),
                ('canceled', models.BooleanField(default=False)),
                ('room_name', models.CharField(max_length=60, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articlesApi.Article')),
                ('discussion_topic', models.ManyToManyField(to='livechatApi.Category')),
                ('recipient', models.ManyToManyField(related_name='is_recipient', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingReviewQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('order', models.SmallIntegerField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='livechatApi.MeetingReviewChoice')),
                ('choices', models.ManyToManyField(to='livechatApi.MeetingReviewChoice')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='livechatApi.LCRoom')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_rate', models.IntegerField(default=0)),
                ('conversation_rate', models.IntegerField(default=0)),
                ('attendace', models.BooleanField(default=False)),
                ('accept_working_with', models.BooleanField(default=False)),
                ('issues', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('attended', models.ManyToManyField(related_name='users_attended_meeting', to=settings.AUTH_USER_MODEL)),
                ('issue_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='livechatApi.MeetingReviewChoice')),
                ('not_attended', models.ManyToManyField(related_name='user_not_attended_meeting', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomName', to='livechatApi.LCRoom')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='livechatApi.LCRoom')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
