export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const GET_USER_START = "GET_USER_START";
export const GET_USER_FAIL = "GET_USER_FAIL";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";

export const GET_LIKES_START = "LIKES_START";
export const GET_LIKES_FAIL = "LIKES_FAIL";
export const GET_LIKES_SUCCESS = "LIKES_SUCCESS";

export const GET_LIKE_DETAIL_START = "GET_LIKE_DETAIL_START";
export const GET_LIKE_DETAIL_FAIL = "GET_LIKE_DETAIL_FAIL";
export const GET_LIKE_DETAIL_SUCCESS = "GET_LIKE_DETAIL_SUCCESS";

export const LIKE_START = "LIKE_START";
export const LIKE_FAIL = "LIKE_FAIL";
export const LIKE_SUCCESS = "LIKE_SUCCESS";

export const GET_RATING_START = "GET_RATING_START";
export const GET_RATING_FAIL = "GET_RATING_FAIL";
export const GET_RATING_SUCCESS = "GET_RATING_SUCCESS";

export const CREATE_RATING_START = "CREATE_RATING_START";
export const CREATE_RATING_FAIL = "CREATE_RATING_FAIL";
export const CREATE_RATING_SUCCESS = "CREATE_RATING_SUCCESS";

export const CREATE_COMMENT_START = "CREATE_COMMENT_START";
export const CREATE_COMMENT_FAIL = "CREATE_COMMENT_FAIL";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";

export const GET_COMMENT_LIST_START = "GET_COMMENT_LIST_START";
export const GET_COMMENTS_LIST_FAIL = "GET_COMMENTS_LIST_FAIL";
export const GET_COMMENTS_LIST_SUCCESS = "GET_COMMENTS_LIST_SUCCESS";

export const GET_COMMENT_DETAIL_START = "GET_COMMENT_DETAIL_START";
export const GET_COMMENT_DETAIL_FAIL = "GET_COMMENT_DETAIL_FAIL";
export const GET_COMMENT_DETAIL_SUCCESS = "GET_COMMENT_DETAIL_SUCCESS";

export const PUT_COMMENT_START = "PUT_COMMENT_START,";
export const PUT_COMMENT_FAIL = "PUT_COMMENT_FAIL,";
export const PUT_COMMENT_SUCCESS = "PUT_COMMENT_SUCCESS";

export const CREATE_ARTICLE_START = "CREATE_ARTICLE_START";
export const CREATE_ARTICLE_FAIL = "CREATE_ARTICLE_FAIL";
export const CREATE_ARTICLE_SUCCESS = "CREATE_ARTICLE_SUCCESS";

export const GET_ARTICLE_LIST_START = "GET_ARTICLE_LIST_START";
export const GET_ARTICLES_LIST_FAIL = "GET_ARTICLES_LIST_FAIL";
export const GET_ARTICLES_LIST_SUCCESS = "GET_ARTICLES_LIST_SUCCESS";

export const GET_ARTICLE_DETAIL_START = "GET_ARTICLE_DETAIL_START";
export const GET_ARTICLE_DETAIL_FAIL = "GET_ARTICLE_DETAIL_FAIL";
export const GET_ARTICLE_DETAIL_SUCCESS = "GET_ARTICLE_DETAIL_SUCCESS";

export const GET_ASSIGNMENT_LIST_START = "GET_ASSIGNMENT_LIST_START";
export const GET_ASSIGNMENTS_LIST_FAIL = "GET_ASSIGNMENTS_LIST_FAIL";
export const GET_ASSIGNMENTS_LIST_SUCCESS = "GET_ASSIGNMENTS_LIST_SUCCESS";

export const GET_ASSIGNMENT_DETAIL_START = "GET_ASSIGNMENT_DETAIL_START";
export const GET_ASSIGNMENT_DETAIL_FAIL = "GET_ASSIGNMENT_DETAIL_FAIL";
export const GET_ASSIGNMENT_DETAIL_SUCCESS = "GET_ASSIGNMENT_DETAIL_SUCCESS";

export const GET_ASSIGNMENT_CHOICES_START = "GET_ASSIGNMENT_CHOICES_START";
export const GET_ASSIGNMENTS_CHOICES_FAIL = "GET_ASSIGNMENTS_CHOICES_FAIL";
export const GET_ASSIGNMENTS_CHOICES_SUCCESS = "GET_ASSIGNMENTS_CHOICES_SUCCESS";

export const CREATE_ASSIGNMENT_START = "CREATE_ASSIGNMENT_START";
export const CREATE_ASSIGNMENT_FAIL = "CREATE_ASSIGNMENT_FAIL";
export const CREATE_ASSIGNMENT_SUCCESS = "CREATE_ASSIGNMENT_SUCCESS";

export const GET_GRADED_ASSIGNMENT_LIST_START = "GET_GRADED_ASSIGNMENT_LIST_START";
export const GET_GRADED_ASSIGNMENTS_LIST_FAIL = "GET_GRADED_ASSIGNMENTS_LIST_FAIL";
export const GET_GRADED_ASSIGNMENTS_LIST_SUCCESS = "GET_GRADED_ASSIGNMENTS_LIST_SUCCESS";