export const GET_USER_COLLABORATION_LIST_START = "GET_USER_COLLABORATION_LIST_START";
export const GET_USER_COLLABORATION_LIST_FAIL = "GET_USER_COLLABORATION_LIST_FAIL";
export const GET_USER_COLLABORATION_LIST_SUCCESS = "GET_USER_COLLABORATION_LIST_SUCCESS";

export const PUT_USER_COLLABORATION_START = "PUT_USER_COLLABORATION_START";
export const PUT_USER_COLLABORATION_FAIL = "PUT_USER_COLLABORATION_FAIL";
export const PUT_USER_COLLABORATION_SUCCESS = "PUT_USER_COLLABORATION_SUCCESS";
