export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const GET_USER_START = "GET_USER_START";
export const GET_USER_FAIL = "GET_USER_FAIL";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";

export const GET_USER_PROFILE_INFO_START = "GET_USER_PROFILE_INFO_START";
export const GET_USER_PROFILE_INFO_FAIL = "GET_USER_PROFILE_INFO_FAIL";
export const GET_USER_PROFILE_INFO_SUCCESS = "GET_USER_PROFILE_INFO_SUCCESS";

export const GET_LIKES_START = "LIKES_START";
export const GET_LIKES_FAIL = "LIKES_FAIL";
export const GET_LIKES_SUCCESS = "LIKES_SUCCESS";

export const GET_LIKE_DETAIL_START = "GET_LIKE_DETAIL_START";
export const GET_LIKE_DETAIL_FAIL = "GET_LIKE_DETAIL_FAIL";
export const GET_LIKE_DETAIL_SUCCESS = "GET_LIKE_DETAIL_SUCCESS";

export const LIKE_START = "LIKE_START";
export const LIKE_FAIL = "LIKE_FAIL";
export const LIKE_SUCCESS = "LIKE_SUCCESS";

export const GET_RATING_START = "GET_RATING_START";
export const GET_RATING_FAIL = "GET_RATING_FAIL";
export const GET_RATING_SUCCESS = "GET_RATING_SUCCESS";

export const CREATE_RATING_START = "CREATE_RATING_START";
export const CREATE_RATING_FAIL = "CREATE_RATING_FAIL";
export const CREATE_RATING_SUCCESS = "CREATE_RATING_SUCCESS";

export const GET_ROOM_DETAIL_START = "GET_ROOM_DETAIL_START";
export const GET_ROOM_DETAIL_FAIL = "GET_ROOM_DETAIL_FAIL";
export const GET_ROOM_DETAIL_SUCCESS = "GET_ROOM_DETAIL_SUCCESS";

export const CREATE_COMMENT_START = "CREATE_COMMENT_START";
export const CREATE_COMMENT_FAIL = "CREATE_COMMENT_FAIL";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";

export const GET_COMMENT_LIST_START = "GET_COMMENT_LIST_START";
export const GET_COMMENTS_LIST_FAIL = "GET_COMMENTS_LIST_FAIL";
export const GET_COMMENTS_LIST_SUCCESS = "GET_COMMENTS_LIST_SUCCESS";

export const GET_COMMENT_DETAIL_START = "GET_COMMENT_DETAIL_START";
export const GET_COMMENT_DETAIL_FAIL = "GET_COMMENT_DETAIL_FAIL";
export const GET_COMMENT_DETAIL_SUCCESS = "GET_COMMENT_DETAIL_SUCCESS";

export const PUT_COMMENT_START = "PUT_COMMENT_START,";
export const PUT_COMMENT_FAIL = "PUT_COMMENT_FAIL,";
export const PUT_COMMENT_SUCCESS = "PUT_COMMENT_SUCCESS";

export const CREATE_ARTICLE_START = "CREATE_ARTICLE_START";
export const CREATE_ARTICLE_FAIL = "CREATE_ARTICLE_FAIL";
export const CREATE_ARTICLE_SUCCESS = "CREATE_ARTICLE_SUCCESS";

export const GET_ARTICLE_LIST_START = "GET_ARTICLE_LIST_START";
export const GET_ARTICLES_LIST_FAIL = "GET_ARTICLES_LIST_FAIL";
export const GET_ARTICLES_LIST_SUCCESS = "GET_ARTICLES_LIST_SUCCESS";

export const GET_ARTICLE_DETAIL_START = "GET_ARTICLE_DETAIL_START";
export const GET_ARTICLE_DETAIL_FAIL = "GET_ARTICLE_DETAIL_FAIL";
export const GET_ARTICLE_DETAIL_SUCCESS = "GET_ARTICLE_DETAIL_SUCCESS";

export const GET_ASSIGNMENT_LIST_START = "GET_ASSIGNMENT_LIST_START";
export const GET_ASSIGNMENTS_LIST_FAIL = "GET_ASSIGNMENTS_LIST_FAIL";
export const GET_ASSIGNMENTS_LIST_SUCCESS = "GET_ASSIGNMENTS_LIST_SUCCESS";

export const GET_ASSIGNMENT_DETAIL_START = "GET_ASSIGNMENT_DETAIL_START";
export const GET_ASSIGNMENT_DETAIL_FAIL = "GET_ASSIGNMENT_DETAIL_FAIL";
export const GET_ASSIGNMENT_DETAIL_SUCCESS = "GET_ASSIGNMENT_DETAIL_SUCCESS";

export const GET_ASSIGNMENT_CHOICES_START = "GET_ASSIGNMENT_CHOICES_START";
export const GET_ASSIGNMENTS_CHOICES_FAIL = "GET_ASSIGNMENTS_CHOICES_FAIL";
export const GET_ASSIGNMENTS_CHOICES_SUCCESS = "GET_ASSIGNMENTS_CHOICES_SUCCESS";

export const CREATE_ASSIGNMENT_START = "CREATE_ASSIGNMENT_START";
export const CREATE_ASSIGNMENT_FAIL = "CREATE_ASSIGNMENT_FAIL";
export const CREATE_ASSIGNMENT_SUCCESS = "CREATE_ASSIGNMENT_SUCCESS";

export const GET_GRADED_ASSIGNMENT_LIST_START = "GET_GRADED_ASSIGNMENT_LIST_START";
export const GET_GRADED_ASSIGNMENTS_LIST_FAIL = "GET_GRADED_ASSIGNMENTS_LIST_FAIL";
export const GET_GRADED_ASSIGNMENTS_LIST_SUCCESS = "GET_GRADED_ASSIGNMENTS_LIST_SUCCESS";

export const CREATE_MEETING_START = "CREATE_MEETING_START";
export const CREATE_MEETING_FAIL = "CREATE_MEETING_FAIL";
export const CREATE_MEETING_SUCCESS = "CREATE_MEETING_SUCCESS";

export const GET_MEETING_LIST_START = "GET_MEETING_LIST_START";
export const GET_MEETINGS_LIST_FAIL = "GET_MEETINGS_LIST_FAIL";
export const GET_MEETINGS_LIST_SUCCESS = "GET_MEETINGS_LIST_SUCCESS";

export const GET_RECEVIED_MEETING_LIST_START = "GET_RECEVIED_MEETING_LIST_START";
export const GET_RECEVIED_MEETINGS_LIST_SUCCESS = "GET_RECEVIED_MEETINGS_LIST_FAIL";
export const GET_RECEVIED_MEETINGS_LIST_FAIL = "GET_RECEVIED_MEETINGS_LIST_SUCCESS";

export const GET_BOOKED_MEETING_LIST_START = "GET_BOOKED_MEETING_LIST_START";
export const GET_BOOKED_MEETINGS_LIST_SUCCESS = "GET_BOOKED_MEETINGS_LIST_SUCCESS";
export const GET_BOOKED_MEETINGS_LIST_FAIL = "GET_BOOKED_MEETINGS_LIST_FAIL";

export const GET_MEETING_DETAIL_START = "GET_MEETING_DETAIL_START";
export const GET_MEETING_DETAIL_FAIL = "GET_MEETING_DETAIL_FAIL";
export const GET_MEETING_DETAIL_SUCCESS = "GET_MEETING_DETAIL_SUCCESS";

export const PUT_MEETING_DETAIL_START = "PUT_MEETING_DETAIL_START";
export const PUT_MEETING_DETAIL_SUCCESS = "PUT_MEETING_DETAIL_SUCCESS";
export const PUT_MEETING_DETAIL_FAIL = "PUT_MEETING_DETAIL_FAIL";

export const CANCEL_MEETING_START = "CANCEL_MEETING_START,";
export const CANCEL_MEETING_FAIL = "CANCEL_MEETING_FAIL,";
export const CANCEL_MEETING_SUCCESS = "CANCEL_MEETING_SUCCESS";

export const GET_PROFILE_DETAIL_START = "GET_PROFILE_DETAIL_START";
export const GET_PROFILE_DETAIL_FAIL = "GET_PROFILE_DETAIL_FAIL";
export const GET_PROFILE_DETAIL_SUCCESS = "GET_PROFILE_DETAIL_SUCCESS";

export const GET_PROFILE_ACCOUNT_DETAIL_START = "GET_PROFILE_ACCOUNT_DETAIL_START";
export const GET_PROFILE_ACCOUNT_DETAIL_FAIL = "GET_PROFILE_ACCOUNT_DETAIL_FAIL";
export const GET_PROFILE_ACCOUNT_DETAIL_SUCCESS = "GET_PROFILE_ACCOUNT_DETAIL_SUCCESS";

export const PUT_PROFILE_ACCOUNT_DETAIL_START = "PUT_PROFILE_ACCOUNT_DETAIL_START";
export const PUT_PROFILE_ACCOUNT_DETAIL_SUCCESS = "PUT_PROFILE_ACCOUNT_DETAIL_SUCCESS";
export const PUT_PROFILE_ACCOUNT_DETAIL_FAIL = "PUT_PROFILE_ACCOUNT_DETAIL_FAIL";

export const GET_PROFILE_MR_START = "GET_PROFILE_MR_START"
export const GET_PROFILE_MR_FAIL = "GET_PROFILE_MR_FAIL"
export const GET_PROFILE_MR_SUCCESS = "GET_PROFILE_MR_SUCCESS"

export const GET_PROFILE_INFO_START = "GET_PROFILE_INFO_START";
export const GET_PROFILE_INFO_FAIL = "GET_PROFILE_INFO_FAIL";
export const GET_PROFILE_INFO_SUCCESS = "GET_PROFILE_INFO_SUCCESS";

export const PUT_PROFILE_INFO_START = "PUT_PROFILE_INFO_START";
export const PUT_PROFILE_INFO_SUCCESS = "PUT_PROFILE_INFO_SUCCESS";
export const PUT_PROFILE_INFO_FAIL = "PUT_PROFILE_INFO_FAIL";

export const GET_PROFILE_ARTICLE_LIST_START = "GET_PROFILE_ARTICLE_LIST_START";
export const GET_PROFILE_ARTICLES_LIST_FAIL = "GET_PROFILE_ARTICLES_LIST_FAIL";
export const GET_PROFILE_ARTICLES_LIST_SUCCESS = "GET_PROFILE_ARTICLES_LIST_SUCCESS";

export const GET_PROFILE_ARTICLE_DETAIL_START = "GET_PROFILE_ARTICLE_DETAIL_START";
export const GET_PROFILE_ARTICLE_DETAIL_FAIL = "GET_PROFILE_ARTICLE_DETAIL_FAIL";
export const GET_PROFILE_ARTICLE_DETAIL_SUCCESS = "GET_PROFILE_ARTICLE_DETAIL_SUCCESS";

export const PUT_PROFILE_ARTICLE_DETAIL_START = "PUT_PROFILE_ARTICLE_DETAIL_START";
export const PUT_PROFILE_ARTICLE_DETAIL_FAIL = "PUT_PROFILE_ARTICLE_DETAIL_FAIL";
export const PUT_PROFILE_ARTICLE_DETAIL_SUCCESS = "PUT_PROFILE_ARTICLE_DETAIL_SUCCESS";

export const DELETE_PROFILE_ARTICLE_DETAIL_FAIL = "DELETE_PROFILE_ARTICLE_DETAIL_FAIL";
export const DELETE_PROFILE_ARTICLE_DETAIL_SUCCESS = "DELETE_PROFILE_ARTICLE_DETAIL_SUCCESS";

export const CREATE_INCENTIVE_START = "CREATE_INCENTIVE_START";
export const CREATE_INCENTIVE_FAIL = "CREATE_INCENTIVE_FAIL";
export const CREATE_INCENTIVE_SUCCESS = "CREATE_INCENTIVE_SUCCESS";

export const GET_INCENTIVE_LIST_START = "GET_INCENTIVE_LIST_START";
export const GET_INCENTIVE_LIST_SUCCESS = "GET_INCENTIVE_LIST_SUCCESS";
export const GET_INCENTIVE_LIST_FAIL = "GET_INCENTIVE_LIST_FAIL";

export const GET_INCENTIVE_DETAIL_START = "GET_INCENTIVE_DETAIL_START";
export const GET_INCENTIVE_DETAIL_FAIL = "GET_INCENTIVE_DETAIL_FAIL";
export const GET_INCENTIVE_DETAIL_SUCCESS = "GET_INCENTIVE_DETAIL_SUCCESS";

export const CREATE_MEETING_REVIEW_DETAIL_START = "CREATE_MEETING_REVIEW_DETAIL_START";
export const CREATE_MEETING_REVIEW_DETAIL_SUCCESS = "CREATE_MEETING_REVIEW_DETAIL_SUCCESS";
export const CREATE_MEETING_REVIEW_DETAIL_FAIL = "CREATE_MEETING_REVIEW_DETAIL_FAIL";

export const GET_SURVEY_LIST_START = "GET_SURVEY_LIST_START";
export const GET_SURVEYS_LIST_FAIL = "GET_SURVEYS_LIST_FAIL";
export const GET_SURVEYS_LIST_SUCCESS = "GET_SURVEYS_LIST_SUCCESS";

export const GET_SURVEY_DETAIL_START = "GET_SURVEY_DETAIL_START";
export const GET_SURVEY_DETAIL_FAIL = "GET_SURVEY_DETAIL_FAIL";
export const GET_SURVEY_DETAIL_SUCCESS = "GET_SURVEY_DETAIL_SUCCESS";

export const GET_SURVEY_CHOICES_START = "GET_SURVEY_CHOICES_START";
export const GET_SURVEYS_CHOICES_FAIL = "GET_SURVEYS_CHOICES_FAIL";
export const GET_SURVEYS_CHOICES_SUCCESS = "GET_SURVEYS_CHOICES_SUCCESS";

export const CREATE_SURVEY_START = "CREATE_SURVEY_START";
export const CREATE_SURVEY_FAIL = "CREATE_SURVEY_FAIL";
export const CREATE_SURVEY_SUCCESS = "CREATE_SURVEY_SUCCESS";

export const GET_GRADED_SURVEY_LIST_START = "GET_GRADED_SURVEY_LIST_START";
export const GET_GRADED_SURVEYS_LIST_FAIL = "GET_GRADED_SURVEYS_LIST_FAIL";
export const GET_GRADED_SURVEYS_LIST_SUCCESS = "GET_GRADED_SURVEYS_LIST_SUCCESS";

export const GET_GRADED_SURVEY_DETAIL_START = "GET_GRADED_SURVEY_DETAIL_START"
export const GET_GRADED_SURVEYS_DETAIL_SUCCESS = "GET_GRADED_SURVEYS_DETAIL_SUCCESS"
export const GET_GRADED_SURVEYS_DETAIL_FAIL = "GET_GRADED_SURVEYS_DETAIL_FAIL"

export const GET_PROFILE_SURVEY_LIST_START = "GET_PROFILE_SURVEY_LIST_START";
export const GET_PROFILE_SURVEY_LIST_SUCCESS = "GET_PROFILE_SURVEY_LIST_SUCCESS";
export const GET_PROFILE_SURVEY_LIST_FAIL = "GET_PROFILE_SURVEY_LIST_FAIL";
export const GET_PROFILE_SURVEY_DETAIL_START = "GET_PROFILE_SURVEY_DETAIL_START";
export const GET_PROFILE_SURVEY_DETAIL_FAIL = "GET_PROFILE_SURVEY_DETAIL_FAIL";
export const GET_PROFILE_SURVEY_DETAIL_SUCCESS = "GET_PROFILE_SURVEY_DETAIL_SUCCESS";
export const PUT_PROFILE_SURVEY_DETAIL_START = "PUT_PROFILE_SURVEY_DETAIL_START";
export const PUT_PROFILE_SURVEY_DETAIL_FAIL = "PUT_PROFILE_SURVEY_DETAIL_FAIL";
export const PUT_PROFILE_SURVEY_DETAIL_SUCCESS = "PUT_PROFILE_SURVEY_DETAIL_SUCCESS";
export const DELETE_PROFILE_SURVEY_DETAIL_FAIL = "DELETE_PROFILE_SURVEY_DETAIL_FAIL";
export const DELETE_PROFILE_SURVEY_DETAIL_SUCCESS = "DELETE_PROFILE_SURVEY_DETAIL_SUCCESS";

export const GET_PROFILE_NOTIFICATION_LIST_START = "GET_PROFILE_NOTIFICATION_LIST_START";
export const GET_PROFILE_NOTIFICATIONS_LIST_FAIL = "GET_PROFILE_NOTIFICATIONS_LIST_FAIL";
export const GET_PROFILE_NOTIFICATIONS_LIST_SUCCESS = "GET_PROFILE_NOTIFICATIONS_LIST_SUCCESS";
export const GET_PROFILE_NOTIFICATION_DETAIL_START = "GET_PROFILE_NOTIFICATION_DETAIL_START";
export const GET_PROFILE_NOTIFICATION_DETAIL_FAIL = "GET_PROFILE_NOTIFICATION_DETAIL_FAIL";
export const GET_PROFILE_NOTIFICATION_DETAIL_SUCCESS = "GET_PROFILE_NOTIFICATION_DETAIL_SUCCESS";
export const PUT_PROFILE_NOTIFICATION_LIST_START = "PUT_PROFILE_NOTIFICATION_LIST_START";
export const PUT_PROFILE_NOTIFICATION_LIST_FAIL = "PUT_PROFILE_NOTIFICATION_LIST_FAIL";
export const PUT_PROFILE_NOTIFICATION_LIST_SUCCESS = "PUT_PROFILE_NOTIFICATION_LIST_SUCCESS";
export const PUT_PROFILE_NOTIFICATION_DETAIL_START = "PUT_PROFILE_NOTIFICATION_DETAIL_START";
export const PUT_PROFILE_NOTIFICATION_DETAIL_FAIL = "PUT_PROFILE_NOTIFICATION_DETAIL_FAIL";
export const PUT_PROFILE_NOTIFICATION_DETAIL_SUCCESS = "PUT_PROFILE_NOTIFICATION_DETAIL_SUCCESS";
export const DELETE_PROFILE_NOTIFICATION_DETAIL_FAIL = "DELETE_PROFILE_NOTIFICATION_DETAIL_FAIL";
export const DELETE_PROFILE_NOTIFICATION_DETAIL_SUCCESS = "DELETE_PROFILE_NOTIFICATION_DETAIL_SUCCESS";

export const CREATE_INQUIRY_START = "CREATE_INQUIRY_START";
export const CREATE_INQUIRY_FAIL = "CREATE_INQUIRY_FAIL";
export const CREATE_INQUIRY_SUCCESS = "CREATE_INQUIRY_SUCCESS";

export const GET_INQUIRY_LIST_START = "GET_INQUIRY_LIST_START";
export const GET_INQUIRIES_LIST_FAIL = "GET_INQUIRIES_LIST_FAIL";
export const GET_INQUIRIES_LIST_SUCCESS = "GET_INQUIRIES_LIST_SUCCESS";

export const GET_INQUIRY_DETAIL_START = "GET_INQUIRY_DETAIL_START";
export const GET_INQUIRY_DETAIL_FAIL = "GET_INQUIRY_DETAIL_FAIL";
export const GET_INQUIRY_DETAIL_SUCCESS = "GET_INQUIRY_DETAIL_SUCCESS";

export const GET_PROFILE_INQUIRY_LIST_START = "GET_PROFILE_INQUIRY_LIST_START";
export const GET_PROFILE_INQUIRY_LIST_SUCCESS = "GET_PROFILE_INQUIRY_LIST_SUCCESS";
export const GET_PROFILE_INQUIRY_LIST_FAIL = "GET_PROFILE_INQUIRY_LIST_FAIL";
export const GET_PROFILE_INQUIRY_DETAIL_START = "GET_PROFILE_INQUIRY_DETAIL_START";
export const GET_PROFILE_INQUIRY_DETAIL_FAIL = "GET_PROFILE_INQUIRY_DETAIL_FAIL";
export const GET_PROFILE_INQUIRY_DETAIL_SUCCESS = "GET_PROFILE_INQUIRY_DETAIL_SUCCESS";
export const PUT_PROFILE_INQUIRY_DETAIL_START = "PUT_PROFILE_INQUIRY_DETAIL_START";
export const PUT_PROFILE_INQUIRY_DETAIL_FAIL = "PUT_PROFILE_INQUIRY_DETAIL_FAIL";
export const PUT_PROFILE_INQUIRY_DETAIL_SUCCESS = "PUT_PROFILE_INQUIRY_DETAIL_SUCCESS";
export const DELETE_PROFILE_INQUIRY_DETAIL_FAIL = "DELETE_PROFILE_INQUIRY_DETAIL_FAIL";
export const DELETE_PROFILE_INQUIRY_DETAIL_SUCCESS = "DELETE_PROFILE_INQUIRY_DETAIL_SUCCESS";