export const GET_PROJECT_LIKES_START = "PROJECT_LIKES_START";
export const GET_PROJECT_LIKES_FAIL = "PROJECT_LIKES_FAIL";
export const GET_PROJECT_LIKES_SUCCESS = "PROJECT_LIKES_SUCCESS";

export const GET_PROJECT_LIKE_DETAIL_START = "GET_PROJECT_LIKE_DETAIL_START";
export const GET_PROJECT_LIKE_DETAIL_FAIL = "GET_PROJECT_LIKE_DETAIL_FAIL";
export const GET_PROJECT_LIKE_DETAIL_SUCCESS = "GET_PROJECT_LIKE_DETAIL_SUCCESS";

export const PROJECT_LIKE_START = "PROJECT_LIKE_START";
export const PROJECT_LIKE_FAIL = "PROJECT_LIKE_FAIL";
export const PROJECT_LIKE_SUCCESS = "PROJECT_LIKE_SUCCESS";