export const GET_PROFILE_WORKSHOP_LIST_START = "GET_PROFILE_WORKSHOP_LIST_START";
export const GET_PROFILE_WORKSHOPS_LIST_FAIL = "GET_PROFILE_WORKSHOPS_LIST_FAIL";
export const GET_PROFILE_WORKSHOPS_LIST_SUCCESS = "GET_PROFILE_WORKSHOPS_LIST_SUCCESS";

export const GET_PROFILE_WORKSHOP_DETAIL_START = "GET_PROFILE_WORKSHOP_DETAIL_START";
export const GET_PROFILE_WORKSHOP_DETAIL_FAIL = "GET_PROFILE_WORKSHOP_DETAIL_FAIL";
export const GET_PROFILE_WORKSHOP_DETAIL_SUCCESS = "GET_PROFILE_WORKSHOP_DETAIL_SUCCESS";

export const PUT_PROFILE_WORKSHOP_DETAIL_START = "PUT_PROFILE_WORKSHOP_DETAIL_START";
export const PUT_PROFILE_WORKSHOP_DETAIL_FAIL = "PUT_PROFILE_WORKSHOP_DETAIL_FAIL";
export const PUT_PROFILE_WORKSHOP_DETAIL_SUCCESS = "PUT_PROFILE_WORKSHOP_DETAIL_SUCCESS";

export const DELETE_PROFILE_WORKSHOP_DETAIL_FAIL = "DELETE_PROFILE_WORKSHOP_DETAIL_FAIL";
export const DELETE_PROFILE_WORKSHOP_DETAIL_SUCCESS = "DELETE_PROFILE_WORKSHOP_DETAIL_SUCCESS";