# Generated by Django 2.2.3 on 2019-10-01 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignmentApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentchoices',
            name='assignment_choice',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='assignment_type',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='survey',
        ),
    ]
