# Generated by Django 2.2.3 on 2019-10-01 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignmentApi', '0003_auto_20191001_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='startup',
            new_name='teacher',
        ),
    ]
