# Generated by Django 2.2.3 on 2019-10-18 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignmentApi', '0004_auto_20191001_0312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentchoices',
            old_name='assignment_choices',
            new_name='feedback_types',
        ),
        migrations.RenameField(
            model_name='assignmentchoices',
            old_name='assignment_choice',
            new_name='to_assignment',
        ),
    ]
