# Generated by Django 2.2.3 on 2020-02-02 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignmentApi', '0005_auto_20191018_2316'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Survey',
        ),
    ]
