# Generated by Django 2.2.3 on 2020-02-12 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, choices=[('Amazon.com Gift Card', 'Amazon.com Gift Card'), ('Uber Gift Card', 'Uber Gift Card'), ('CineCash', 'CineCash'), ('Spotify Gift Card', 'Spotify Gift Card'), ('Spotify Gift Card', 'Spotify Gift Card'), ('Walmart Gift Card', 'Walmart Gift Card'), ("Domino's Gift Card", "Domino's Gift Card"), ('Burger King Gift Card', 'Burger King Gift Card'), ('Best Buy Gift Card', 'Best Buy Gift Card'), ('other', 'other')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Incentive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('activated', models.BooleanField(default=False)),
                ('claimed', models.BooleanField(default=False)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('currency', models.CharField(blank=True, max_length=5, null=True)),
                ('cardClaimCode', models.CharField(blank=True, max_length=30, null=True)),
                ('requestId', models.CharField(blank=True, max_length=30, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentive_buyer', to=settings.AUTH_USER_MODEL)),
                ('incentive_brand', models.ManyToManyField(to='incentivesApi.Brand')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentive_recipient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
